export declare const YLabel: import("styled-components").IStyledComponent<"web", {
    className?: string | undefined;
    color?: string | undefined;
    height?: string | number | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    max?: string | number | undefined;
    media?: string | undefined;
    method?: string | undefined;
    min?: string | number | undefined;
    name?: string | undefined;
    style?: import("react").CSSProperties | undefined;
    target?: string | undefined;
    type?: string | undefined;
    width?: string | number | undefined;
    role?: import("react").AriaRole | undefined;
    tabIndex?: number | undefined;
    crossOrigin?: "" | "anonymous" | "use-credentials" | undefined;
    accentHeight?: string | number | undefined;
    accumulate?: "none" | "sum" | undefined;
    additive?: "replace" | "sum" | undefined;
    alignmentBaseline?: "inherit" | "alphabetic" | "hanging" | "ideographic" | "mathematical" | "auto" | "baseline" | "before-edge" | "text-before-edge" | "middle" | "central" | "after-edge" | "text-after-edge" | undefined;
    allowReorder?: "yes" | "no" | undefined;
    alphabetic?: string | number | undefined;
    amplitude?: string | number | undefined;
    arabicForm?: "initial" | "medial" | "terminal" | "isolated" | undefined;
    ascent?: string | number | undefined;
    attributeName?: string | undefined;
    attributeType?: string | undefined;
    autoReverse?: (boolean | "true" | "false") | undefined;
    azimuth?: string | number | undefined;
    baseFrequency?: string | number | undefined;
    baselineShift?: string | number | undefined;
    baseProfile?: string | number | undefined;
    bbox?: string | number | undefined;
    begin?: string | number | undefined;
    bias?: string | number | undefined;
    by?: string | number | undefined;
    calcMode?: string | number | undefined;
    capHeight?: string | number | undefined;
    clip?: string | number | undefined;
    clipPath?: string | undefined;
    clipPathUnits?: string | number | undefined;
    clipRule?: string | number | undefined;
    colorInterpolation?: string | number | undefined;
    colorInterpolationFilters?: "inherit" | "auto" | "sRGB" | "linearRGB" | undefined;
    colorProfile?: string | number | undefined;
    colorRendering?: string | number | undefined;
    contentScriptType?: string | number | undefined;
    contentStyleType?: string | number | undefined;
    cursor?: string | number | undefined;
    cx?: string | number | undefined;
    cy?: string | number | undefined;
    d?: string | undefined;
    decelerate?: string | number | undefined;
    descent?: string | number | undefined;
    diffuseConstant?: string | number | undefined;
    direction?: string | number | undefined;
    display?: string | number | undefined;
    divisor?: string | number | undefined;
    dominantBaseline?: string | number | undefined;
    dur?: string | number | undefined;
    dx?: string | number | undefined;
    dy?: string | number | undefined;
    edgeMode?: string | number | undefined;
    elevation?: string | number | undefined;
    enableBackground?: string | number | undefined;
    end?: string | number | undefined;
    exponent?: string | number | undefined;
    externalResourcesRequired?: (boolean | "true" | "false") | undefined;
    fill?: string | undefined;
    fillOpacity?: string | number | undefined;
    fillRule?: "inherit" | "nonzero" | "evenodd" | undefined;
    filter?: string | undefined;
    filterRes?: string | number | undefined;
    filterUnits?: string | number | undefined;
    floodColor?: string | number | undefined;
    floodOpacity?: string | number | undefined;
    focusable?: (boolean | "true" | "false") | "auto" | undefined;
    fontFamily?: string | undefined;
    fontSize?: string | number | undefined;
    fontSizeAdjust?: string | number | undefined;
    fontStretch?: string | number | undefined;
    fontStyle?: string | number | undefined;
    fontVariant?: string | number | undefined;
    fontWeight?: string | number | undefined;
    format?: string | number | undefined;
    fr?: string | number | undefined;
    from?: string | number | undefined;
    fx?: string | number | undefined;
    fy?: string | number | undefined;
    g1?: string | number | undefined;
    g2?: string | number | undefined;
    glyphName?: string | number | undefined;
    glyphOrientationHorizontal?: string | number | undefined;
    glyphOrientationVertical?: string | number | undefined;
    glyphRef?: string | number | undefined;
    gradientTransform?: string | undefined;
    gradientUnits?: string | undefined;
    hanging?: string | number | undefined;
    horizAdvX?: string | number | undefined;
    horizOriginX?: string | number | undefined;
    href?: string | undefined;
    ideographic?: string | number | undefined;
    imageRendering?: string | number | undefined;
    in2?: string | number | undefined;
    in?: string | undefined;
    intercept?: string | number | undefined;
    k1?: string | number | undefined;
    k2?: string | number | undefined;
    k3?: string | number | undefined;
    k4?: string | number | undefined;
    k?: string | number | undefined;
    kernelMatrix?: string | number | undefined;
    kernelUnitLength?: string | number | undefined;
    kerning?: string | number | undefined;
    keyPoints?: string | number | undefined;
    keySplines?: string | number | undefined;
    keyTimes?: string | number | undefined;
    lengthAdjust?: string | number | undefined;
    letterSpacing?: string | number | undefined;
    lightingColor?: string | number | undefined;
    limitingConeAngle?: string | number | undefined;
    local?: string | number | undefined;
    markerEnd?: string | undefined;
    markerHeight?: string | number | undefined;
    markerMid?: string | undefined;
    markerStart?: string | undefined;
    markerUnits?: string | number | undefined;
    markerWidth?: string | number | undefined;
    mask?: string | undefined;
    maskContentUnits?: string | number | undefined;
    maskUnits?: string | number | undefined;
    mathematical?: string | number | undefined;
    mode?: string | number | undefined;
    numOctaves?: string | number | undefined;
    offset?: string | number | undefined;
    opacity?: string | number | undefined;
    operator?: string | number | undefined;
    order?: string | number | undefined;
    orient?: string | number | undefined;
    orientation?: string | number | undefined;
    origin?: string | number | undefined;
    overflow?: string | number | undefined;
    overlinePosition?: string | number | undefined;
    overlineThickness?: string | number | undefined;
    paintOrder?: string | number | undefined;
    panose1?: string | number | undefined;
    path?: string | undefined;
    pathLength?: string | number | undefined;
    patternContentUnits?: string | undefined;
    patternTransform?: string | number | undefined;
    patternUnits?: string | undefined;
    pointerEvents?: string | number | undefined;
    points?: string | undefined;
    pointsAtX?: string | number | undefined;
    pointsAtY?: string | number | undefined;
    pointsAtZ?: string | number | undefined;
    preserveAlpha?: (boolean | "true" | "false") | undefined;
    preserveAspectRatio?: string | undefined;
    primitiveUnits?: string | number | undefined;
    r?: string | number | undefined;
    radius?: string | number | undefined;
    refX?: string | number | undefined;
    refY?: string | number | undefined;
    renderingIntent?: string | number | undefined;
    repeatCount?: string | number | undefined;
    repeatDur?: string | number | undefined;
    requiredExtensions?: string | number | undefined;
    requiredFeatures?: string | number | undefined;
    restart?: string | number | undefined;
    result?: string | undefined;
    rotate?: string | number | undefined;
    rx?: string | number | undefined;
    ry?: string | number | undefined;
    scale?: string | number | undefined;
    seed?: string | number | undefined;
    shapeRendering?: string | number | undefined;
    slope?: string | number | undefined;
    spacing?: string | number | undefined;
    specularConstant?: string | number | undefined;
    specularExponent?: string | number | undefined;
    speed?: string | number | undefined;
    spreadMethod?: string | undefined;
    startOffset?: string | number | undefined;
    stdDeviation?: string | number | undefined;
    stemh?: string | number | undefined;
    stemv?: string | number | undefined;
    stitchTiles?: string | number | undefined;
    stopColor?: string | undefined;
    stopOpacity?: string | number | undefined;
    strikethroughPosition?: string | number | undefined;
    strikethroughThickness?: string | number | undefined;
    string?: string | number | undefined;
    stroke?: string | undefined;
    strokeDasharray?: string | number | undefined;
    strokeDashoffset?: string | number | undefined;
    strokeLinecap?: "inherit" | "butt" | "round" | "square" | undefined;
    strokeLinejoin?: "inherit" | "round" | "miter" | "bevel" | undefined;
    strokeMiterlimit?: string | number | undefined;
    strokeOpacity?: string | number | undefined;
    strokeWidth?: string | number | undefined;
    surfaceScale?: string | number | undefined;
    systemLanguage?: string | number | undefined;
    tableValues?: string | number | undefined;
    targetX?: string | number | undefined;
    targetY?: string | number | undefined;
    textAnchor?: string | undefined;
    textDecoration?: string | number | undefined;
    textLength?: string | number | undefined;
    textRendering?: string | number | undefined;
    to?: string | number | undefined;
    transform?: string | undefined;
    u1?: string | number | undefined;
    u2?: string | number | undefined;
    underlinePosition?: string | number | undefined;
    underlineThickness?: string | number | undefined;
    unicode?: string | number | undefined;
    unicodeBidi?: string | number | undefined;
    unicodeRange?: string | number | undefined;
    unitsPerEm?: string | number | undefined;
    vAlphabetic?: string | number | undefined;
    values?: string | undefined;
    vectorEffect?: string | number | undefined;
    version?: string | undefined;
    vertAdvY?: string | number | undefined;
    vertOriginX?: string | number | undefined;
    vertOriginY?: string | number | undefined;
    vHanging?: string | number | undefined;
    vIdeographic?: string | number | undefined;
    viewBox?: string | undefined;
    viewTarget?: string | number | undefined;
    visibility?: string | number | undefined;
    vMathematical?: string | number | undefined;
    widths?: string | number | undefined;
    wordSpacing?: string | number | undefined;
    writingMode?: string | number | undefined;
    x1?: string | number | undefined;
    x2?: string | number | undefined;
    x?: string | number | undefined;
    xChannelSelector?: string | undefined;
    xHeight?: string | number | undefined;
    xlinkActuate?: string | undefined;
    xlinkArcrole?: string | undefined;
    xlinkHref?: string | undefined;
    xlinkRole?: string | undefined;
    xlinkShow?: string | undefined;
    xlinkTitle?: string | undefined;
    xlinkType?: string | undefined;
    xmlBase?: string | undefined;
    xmlLang?: string | undefined;
    xmlns?: string | undefined;
    xmlnsXlink?: string | undefined;
    xmlSpace?: string | undefined;
    y1?: string | number | undefined;
    y2?: string | number | undefined;
    y?: string | number | undefined;
    yChannelSelector?: string | undefined;
    z?: string | number | undefined;
    zoomAndPan?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "true" | "false") | undefined;
    "aria-autocomplete"?: "list" | "none" | "inline" | "both" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "true" | "false") | undefined;
    "aria-checked"?: boolean | "true" | "false" | "mixed" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "time" | "step" | "true" | "false" | "page" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "true" | "false") | undefined;
    "aria-dropeffect"?: "link" | "none" | "copy" | "execute" | "move" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "true" | "false") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "true" | "false") | undefined;
    "aria-haspopup"?: boolean | "dialog" | "menu" | "true" | "false" | "grid" | "listbox" | "tree" | undefined;
    "aria-hidden"?: (boolean | "true" | "false") | undefined;
    "aria-invalid"?: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "true" | "false") | undefined;
    "aria-multiline"?: (boolean | "true" | "false") | undefined;
    "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "true" | "false" | "mixed" | undefined;
    "aria-readonly"?: (boolean | "true" | "false") | undefined;
    "aria-relevant"?: "text" | "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "true" | "false") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "true" | "false") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    children?: import("react").ReactNode;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onCopyCapture?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onCut?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onCutCapture?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onPaste?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onPasteCapture?: import("react").ClipboardEventHandler<SVGTextElement> | undefined;
    onCompositionEnd?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onCompositionEndCapture?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onCompositionStart?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onCompositionStartCapture?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onCompositionUpdate?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onCompositionUpdateCapture?: import("react").CompositionEventHandler<SVGTextElement> | undefined;
    onFocus?: import("react").FocusEventHandler<SVGTextElement> | undefined;
    onFocusCapture?: import("react").FocusEventHandler<SVGTextElement> | undefined;
    onBlur?: import("react").FocusEventHandler<SVGTextElement> | undefined;
    onBlurCapture?: import("react").FocusEventHandler<SVGTextElement> | undefined;
    onChange?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onChangeCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onBeforeInput?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onBeforeInputCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onInput?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onInputCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onReset?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onResetCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onSubmit?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onSubmitCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onInvalid?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onInvalidCapture?: import("react").FormEventHandler<SVGTextElement> | undefined;
    onLoad?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onError?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onErrorCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onKeyDown?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onKeyDownCapture?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onKeyPress?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onKeyPressCapture?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onKeyUp?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onKeyUpCapture?: import("react").KeyboardEventHandler<SVGTextElement> | undefined;
    onAbort?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onAbortCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onCanPlay?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onCanPlayCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onCanPlayThrough?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onCanPlayThroughCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onDurationChange?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onDurationChangeCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEmptied?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEmptiedCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEncrypted?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEncryptedCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEnded?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onEndedCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadedData?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadedDataCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadedMetadata?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadedMetadataCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadStart?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onLoadStartCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPause?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPauseCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPlay?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPlayCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPlaying?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onPlayingCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onProgress?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onProgressCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onRateChange?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onRateChangeCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onResize?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onResizeCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSeeked?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSeekedCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSeeking?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSeekingCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onStalled?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onStalledCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSuspend?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSuspendCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onTimeUpdate?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onTimeUpdateCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onVolumeChange?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onVolumeChangeCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onWaiting?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onWaitingCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onAuxClick?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onAuxClickCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onClick?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onClickCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onContextMenu?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onContextMenuCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onDoubleClick?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onDoubleClickCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onDrag?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragEnd?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragEndCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragEnter?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragEnterCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragExit?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragExitCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragLeave?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragLeaveCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragOver?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragOverCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragStart?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDragStartCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDrop?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onDropCapture?: import("react").DragEventHandler<SVGTextElement> | undefined;
    onMouseDown?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseDownCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseEnter?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseLeave?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseMove?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseMoveCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseOut?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseOutCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseOver?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseOverCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseUp?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onMouseUpCapture?: import("react").MouseEventHandler<SVGTextElement> | undefined;
    onSelect?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onSelectCapture?: import("react").ReactEventHandler<SVGTextElement> | undefined;
    onTouchCancel?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchCancelCapture?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchEnd?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchEndCapture?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchMove?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchMoveCapture?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchStart?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onTouchStartCapture?: import("react").TouchEventHandler<SVGTextElement> | undefined;
    onPointerDown?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerDownCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerMove?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerMoveCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerUp?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerUpCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerCancel?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerCancelCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerEnter?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerEnterCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerLeave?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerLeaveCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerOver?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerOverCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerOut?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onPointerOutCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onGotPointerCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onGotPointerCaptureCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onLostPointerCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onLostPointerCaptureCapture?: import("react").PointerEventHandler<SVGTextElement> | undefined;
    onScroll?: import("react").UIEventHandler<SVGTextElement> | undefined;
    onScrollCapture?: import("react").UIEventHandler<SVGTextElement> | undefined;
    onWheel?: import("react").WheelEventHandler<SVGTextElement> | undefined;
    onWheelCapture?: import("react").WheelEventHandler<SVGTextElement> | undefined;
    onAnimationStart?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onAnimationStartCapture?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onAnimationEnd?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onAnimationEndCapture?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onAnimationIteration?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onAnimationIterationCapture?: import("react").AnimationEventHandler<SVGTextElement> | undefined;
    onTransitionEnd?: import("react").TransitionEventHandler<SVGTextElement> | undefined;
    onTransitionEndCapture?: import("react").TransitionEventHandler<SVGTextElement> | undefined;
    ref?: import("react").LegacyRef<SVGTextElement> | undefined;
    key?: import("react").Key | null | undefined;
}>;
