# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - "main" # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

environment:
  name: github-pages

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    strategy:
      matrix:
        node-version: [20.9]
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: yarn --frozen-lockfile # default: npm ci
          build_command: yarn build-storybook:production # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
