- name: Deploy Storybook to GitHub Pages
  on:
    push:
      branches:
        - main
  run: |
    cd packages/epo-react-lib
    npm run install
    npm run deploy-storybook -- --ci
  env:
    GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
